-
  name: Webserver Setup
  hosts: all
  become: yes
  tasks:
    - name: Installation Apache
      yum:
        name: httpd
        state: latest
    - name: Installation wget command
      yum:
        name: wget
        state: latest
    - name: Installation git command
      yum:
        name: git
        state: latest
    - name: Get http document from Git
      git:
        repo: "https://github.com/masa03m/webinar01.git"
        dest: "/var/www/html"
    - name: Start service httpd
      service:
        name: httpd
        state: started
    - name: Installation epel-release
      yum:
        name: epel-release
        state: latest
    - name: Installation ClamAV
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - clamav
          - clamav-data
          - clamav-devel
          - clamav-filesystem
          - clamav-update
          - clamd
    - name: ClamAV Pattern File Update
      shell: freshclam
    - name: rm mcmagent dirctory
      file: path=/tmp/mcmagent state=absent
    - name: mkdir mcmagent in /tmp
      file: path=/tmp/mcmagent state=directory owner=root group=root mode=0755
    - name: MCM Agent Module Download
      command: wget http://10.113.1.98/module/cp4mcm_Agents_xlinux_2.0.tar.gz -P /tmp/mcmagent
    - name: MCM Agent Setting File Download
      command: wget http://10.113.1.98/module/APPMGT_silent_install_web.txt -P /tmp/mcmagent
    - name: unarchive source
      command: tar zxvf /tmp/mcmagent/cp4mcm_Agents_xlinux_2.0.tar.gz chdir=/tmp/mcmagent
